/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.json.simple.JSONObject;

/**
 *
 * @author aka
 */
public class PesananPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    
    private int id_menu;
    private String nama;
    private int subtotal;
    private int jumlah;
    private int harga;
    private String kategori;
    private String gambar;
    private BaseForm parentForm;
    
    
    public PesananPanel() {
        initComponents();
    }

    public PesananPanel(int id_menu, String nama, int subtotal, int jumlah, int harga, String kategori, String gambar, BaseForm parentForm) {
        this.id_menu = id_menu;
        this.nama = nama;
        this.subtotal = subtotal;
        this.jumlah = jumlah;
        this.harga = harga;
        this.kategori = kategori;
        this.gambar = gambar;
        this.parentForm = parentForm;
        
        initComponents();
        
        try {
            // dapatkan gambar        
            ImageIcon icon;
            icon = new ImageIcon(new URL("http://localhost:8000/storage/" + this.gambar));
            Image image = icon.getImage();
            image = image.getScaledInstance(130, 110, Image.SCALE_SMOOTH);
            icon = new ImageIcon(image);
            label_image.setIcon(icon);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nama = new javax.swing.JLabel();
        label_subtotal = new javax.swing.JLabel();
        label_kategori = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_image = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        label_jumlah = new javax.swing.JLabel();
        label_harga = new javax.swing.JLabel();
        label_jumlah1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(4, 182, 169));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nama.setFont(new java.awt.Font("Hack", 0, 18)); // NOI18N
        label_nama.setForeground(new java.awt.Color(255, 255, 255));
        label_nama.setText(this.nama);
        add(label_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        label_subtotal.setFont(new java.awt.Font("Hack", 1, 24)); // NOI18N
        label_subtotal.setForeground(new java.awt.Color(255, 255, 255));
        label_subtotal.setText(Long.toString(this.subtotal));
        add(label_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        label_kategori.setFont(new java.awt.Font("Hack", 1, 12)); // NOI18N
        label_kategori.setForeground(new java.awt.Color(255, 255, 255));
        label_kategori.setText(this.kategori);
        add(label_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 560, 10));
        add(label_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 110));

        btn_hapus.setBackground(new java.awt.Color(247, 61, 61));
        btn_hapus.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 120, 40));

        label_jumlah.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        label_jumlah.setForeground(new java.awt.Color(255, 255, 255));
        label_jumlah.setText(Integer.toString(this.jumlah));
        add(label_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        label_harga.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        label_harga.setForeground(new java.awt.Color(255, 255, 255));
        label_harga.setText(Integer.toString(this.harga));
        add(label_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        label_jumlah1.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        label_jumlah1.setForeground(new java.awt.Color(255, 255, 255));
        label_jumlah1.setText("x");
        add(label_jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        
        // TODO add your handling code here:
        
        PemesananForm form = (PemesananForm) this.parentForm;
        form.removePesanan(this.id_menu);
    }//GEN-LAST:event_btn_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_harga;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_jumlah;
    private javax.swing.JLabel label_jumlah1;
    private javax.swing.JLabel label_kategori;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_subtotal;
    // End of variables declaration//GEN-END:variables
}
